version: "3.2"
services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=aggregator
    ports:
      - "28017:27017"
    volumes:
      - mongo:/data/db
#  postgres:
#    image: postgres:alpine
#    environment:
#      - POSTGRES_PASSWORD=docker
#      - POSTGRES_USER=docker
#    ports:
#      - "54321:5432"

volumes:
  mongo: